### ISSUE TITLE
wrong format

### ISSUE THREAD

**Issue by ghost** [Cartucho/mAP#128]
Hi @Cartucho  What could be possible error, i have put screenshot..please help.
![er](https://user-images.githubusercontent.com/58855073/91199154-18893580-e71b-11ea-8365-95e6a470f151.png)

**Comment by qyangaa** [comment]
I had the same issue, and it turns out that the ValueError is raised when your line.split() in main.py line 386 fails. Specifically, my data failed because I included the confidence level in ground truth (=1), which made the line with length 6 (should be 5). You can check if similar stuff happened in your code.
