### ISSUE TITLE
Question Regarding the Shape of mAP Graphs Produced by this Repository

### ISSUE THREAD

**Issue by StephenThacker** [Cartucho/mAP#25]
@Cartucho 

As seen in the below image taken from your ReadMe. Why is there a linear segment in the graph stretching from 0.65 Recall to 1 Recall? I see the same thing when I test my own results. It looks like no points are being plotted after 0.65 Recall and that a linear line is drawn from the last plotted point to the intercept (1,0). 

I previously thought that the curve was produced by plotting precision vs recall as our confidence threshold was decreased until 0. I.e. As 0 confidence corresponds to 1 recall, I would expect to see plotted points along the x-axis up until the point that recall reaches 1. If you have any insight into how I might be misunderstanding this, I would be interested in hearing your thoughts.

![image](https://user-images.githubusercontent.com/35053174/42958105-44fd8442-8b4a-11e8-9f74-d849048afa66.png)

**Comment by Cartucho** [comment]
@StephenThacker Hello and great question!

The linear segment comes from the official PASCAL VOC's code. After calculating the Precision and Recall for each of the predictions we append a final point (with the values: Precision = 0 and Recall=1).

In practice, that last point won't affect the result. When we calculate the precision, at each of the recall points, we multiply the "recall step" by the maximum precision of the following points in the plot (since the precision in monotonically decreasing).
 `ap=sum((mrec(i)-mrec(i-1)).*mpre(i))`, 

where `i` goes from 1 to n.

At the very last step `mprec(n) = 0`, so that very last segment won't affect the result.

Despite this you made me realize that the plots have a mistake: I shouldn't fill in that last part (in light blue) since it won't affect the result. From 0.65 to 1.0 that part should be white under the line segment. I will fix this.

**Comment by Cartucho** [comment]
@StephenThacker I fixed the plots.

![new_plot](https://user-images.githubusercontent.com/15831541/43008995-64dd53ce-8c34-11e8-8a2c-4567b1311910.png)
